### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [gabrielrtakeda/shopping-cart#26]
Hello Sir. I'm a Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design to improve visualization of your project as my Open Source Contribution?

Thanks for your attention.

**Comment by gabrielrtakeda** [comment]
Hi @anharismail, all contributions is very appreciated!
Feel free to open a pull-request to improve the visualization of the project.

Thanks for the interest and, I'll be waiting for a PR.

**Comment by gabrielrtakeda** [comment]
@anharismail, I'll assign this issue to you and, put it in the [dev project's backlog](https://github.com/gabrielrtakeda/shopping-cart/projects/1).
As you move the state of this issue, please, can you move the issue card in the project, please?
When it has finished, is just open and PR and attach it to the `dev` project.

**Comment by leandrocandido** [comment]
I'd like to talk to you... I have some issues... Is it possible?

**Comment by anharismail** [comment]
Logo ideas have been taken.

Thanks for your attention.
